- package.json
- sabre.js
In contrast to the last PR these are things that linters will typically mention and complain about. 
One idea that we use in truffle-security that you might use here is to output the results in YAML; I find that more human friendly. See https://github.com/ConsenSys/truffle-security/blob/master/helpers.js#L216
> use consts and for/of 

- .editorconfig
- .eslintrc.yml
- .gitignore
- lib/eslint.js
- lib/helpers.js
- package-lock.json
- package.json
- sabre.js
> Modified output format to be displayed in ESLint style

- lib/helpers.js
- package-lock.json
- package.json
- sabre.js
Added logic to select the contract with largest `bytecode` in case of multiple contracts are within the same file. This nicely handles the inherit use case along with the default behaviour.
Fixes: #8
> Modified logic to select contract in case of multiple

- lib/helpers.js
- sabre.js
> Fixed issue with relative path imports

- lib/helpers.js
- sabre.js
Use the latest compiler version when >= is used in the pragma.(Fixes #22 )
> Select a correct version #22

- lib/helpers.js
> Use the latest version of 0.x for ^0.x.x

- lib/helpers.js
I think we should add a test file to test every change, in order to prevent to make mistake like me.
> Fix the error of selecting explicit version.

- .gitignore
- lib/helpers.js
- package-lock.json
- sabre.js
> Added support for caching solc-js different versions

- lib/helpers.js
- sabre.js
> Fixed issue with absolute path of contract

- lib/helpers.js
- sabre.js
> Updated the sourceName to be picked from last contract in sourceList

- lib/helpers.js
- sabre.js
> Modified sourcemap resolution for imported contracts

- lib/helpers.js
> Sabre picks incorrect compiler version.

- package.json
- sabre.js
> Optimize downloading compiler version.

- .editorconfig
- lib/helpers.js
- sabre.js
- sample/ERC721.sol
Fixes: #43 
Fixes: #53 
Fixes: #57
> Fixes multiple issues

- lib/compiler.js
- sabre.js
> Added contract name as input argument

- lib/eslint.js
- lib/formatters/text.js
- lib/report.js
- sabre.js
- resolves #67
**Stable**. Review will be appreciated.
- Tweaked **sabre.js** to introduce `text` formatter CLI switch. Text formatter is set **default** one, when formatter option is not specified.
- Tweaked **lib/report.js**:
- `getFormatter()` will use [ESLint `CLIEngine.getFormatter()`](https://eslint.org/docs/developer-guide/nodejs-api#clienginegetformatter) instead of older raw logic. This ensures flexibility and scalability for our future improvements. Custom formatters should be located in **lib/formatters/** directory.
- `issue2EsLint()` now copies entire MythX issue and source code content to each converted issue, because more data is needed for implementation.
- Some code cleanup in **lib/eslint.js** for clarity.
- Implemented [custom text …
> New output formatter "text"

- lib/compiler.js
> Revert "1. lists compilers up to 0.5.10 2. Moves the `latest` property to the top of the file for easier editing"

- README.md
- lib/compiler.js
- sabre.js
- resolves #68 
**Stable**. Requires other proper manual tests.
- Switched mutiple variable names from `snake_case` to `camelCase`.
- Updated usage entry of README.md to describe newly introduced standard CLI options.
- Fixed `Resolver`  initialization config to start looking for imports from input file directory rather than `process.cwd()`.
- https://github.com/blitz-1306/sabre/blob/a73a667f5fc6338b9ffa7285bd4dcd2f00c4094e/sabre.js#L69-L70
- https://github.com/blitz-1306/sabre/blob/a73a667f5fc6338b9ffa7285bd4dcd2f00c4094e/sabre.js#L87-L90
Regards, @blitz-1306.
> Properly resolve npm-style imports

- lib/report.js
- resolves #77 
**Stable**.
- Custom formatter loading should now respect installation directory:
- https://github.com/blitz-1306/sabre/blob/1216af6ff762788d71a42cf5e96d0c542b09bab8/lib/report.js#L1
- https://github.com/blitz-1306/sabre/blob/1216af6ff762788d71a42cf5e96d0c542b09bab8/lib/report.js#L20
Regards, @blitz-1306.
> Fix custom formatter loading error

- lib/client.js
- lib/controllers/analyze.js
- lib/controllers/help.js
- lib/controllers/list.js
- lib/controllers/report.js
- lib/controllers/status.js
- sabre.js
> Refactor cli to be identical to mythx-cli

- README.md
- lib/client.js
- lib/controllers/analyze.js
- lib/controllers/status.js
- sabre.js
> Added login with access token

- package.json
> Updated imports resolver dependency

- README.md
- contracts/Primality.sol
- lib/client.js
- lib/controllers/analyze.js
- lib/formatters/propertyCheckText.js
- lib/report.js
- sabre.js
> Added solfuzz property check command
